### PR TITLE
exercise1

### PR DESCRIPTION
**Pull request by JMSantos77**
Fiz alterações ao código. Vejam o que acham. :)

- - -
This change is [Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3)

### CODE REVIEW

**Review by MarleneA — APPROVED** [review]
> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares and @Esteves346)

**Review by MarleneA — APPROVED** [review]
Revisto e está muito bem

> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3#-:-NfRf6b01NE_hR--lWeK:b-io3k93)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares and @Esteves346)

**Review by Esteves346 — APPROVED** [review]
Nicely structured and simple code

> Reviewed 8 of 8 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3#-:-NfRmjIjEf6JxtjAIfoV:b-3fd7ik)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares)

**Comment by cfmsoares** [comment]
good job!

**Review by cfmsoares — APPROVED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JMSantos77)

**Comment by JMSantos77** [comment]
Obrigado!

**Review by Esteves346 — APPROVED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JMSantos77)

**Review by Esteves346 — APPROVED** [review]
> Reviewed 5 of 5 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/3)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JMSantos77)

**Comment by JMSantos77** [comment]
Olha, obrigado.........

**Pull request merged**
