### PR TITLE
replaced by console.log

### PR DESCRIPTION
**Pull request by JoaoPaiva1222634**
Replaced the printMessage method by console.log

- - -
This change is [Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/2)

### CODE REVIEW

**Review by MarleneA — CHANGES_REQUESTED** [review]
Poderás deixar a função eliminada mas comentada. 

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/2#-:-NfRSRR-DDOevsuCklMr:bwwn5lw)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares)

**Review by JoaoPaiva1222634 — COMMENTED** [review]
és uma chata vou fazer

> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/2#-:-NfRUlLm4Y1lb-DOkrOi:b9kpdrd)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares)

**Review by MarleneA — COMMENTED** [review]
Faz mas é o que te mandam!

> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/2#-:-NfRVDPr3-ofKefOPV0f:bl1w2a2)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @cfmsoares)

**Review by cfmsoares — APPROVED** [review]
very good job!!

> Reviewed 5 of 5 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/GQSoft2-Group01-ClassExercise/Exercise1/2#-:-NfRkYFA-czMGZXlcWRU:b-8lfnr5)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JoaoPaiva1222634)

**Pull request merged**
